apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-application
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://github.com/omerteomim/argo-demo.git'
    targetRevision: dev
    path: chart
    helm:
      valueFiles:
      - environments/dev/values.yml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

